name: venv
channels:
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - numpy=1.22.4
  - pandas=2.0.3
  - pytorch::pytorch=2.1.2
  - pytorch::pytorch-cuda=11.8
  - torchvision=0.16.2
  - pip:
    - nvidia-smi
    - nbclassic